# build environment
FROM node:fermium-buster-slim as build
WORKDIR /app
COPY package*.json ./
RUN npm install 
COPY . .
RUN npm run build

# 2nd stage
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]