pipeline{	
    // agent {label 'kslave1'}	
    agent any
    stages{
        stage('Checkout...'){	    
            steps{
		        echo 'cloning..'
                git credentialsId: "${git_credential}", branch: "${branch}", url: "${gitlab_url}"
            }
        }
        stage('Build......'){	    
            steps{
                sh 'docker build -t registry.gitlab.com/hmcuongit/react-boilerplate:$BUILD_NUMBER .'
            }
        }
        stage('Docker login && push image ......'){	    
            steps{
		            
                withCredentials([usernamePassword(credentialsId: 'lampm_devops', passwordVariable: 'passwd', usernameVariable: 'user')]) {
       
                sh 'echo "${passwd} | docker login registry.gitlab.com -u ${user} --password-stdin" && docker push registry.gitlab.com/hmcuongit/react-boilerplate:$BUILD_NUMBER'
                    
                }
            }
        }
        // stage('Deploy...'){	    
        //     steps{
		//         // sh 'cd ansible-deploy && ansible-playbook -i inventory playbook.yml --extra-vars "tag=$BUILD_NUMBER"'
        //         ansiblePlaybook installation: 'ansible-kslave1', inventory: './ansible-deploy/inventory', playbook: './ansible-deploy/playbook.yml', extras: '--extra-vars tag=$BUILD_NUMBER'
        //     }        
     
        // }
    }

}